### Signup
POST http://localhost:3000/signup
Content-Type: application/json

{
  "username": "neithal",
  "password": "neithuz_dev0000"
}
###

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "neithal",
  "password": "neithuz_dev0000"
}
###

### Get All Courses
GET http://localhost:3000/courses

###

### Purchase Course (replace courseId and token)
POST http://localhost:3000/purchase/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5laXRoYWwiLCJpYXQiOjE3NTA2ODA4MTYsImV4cCI6MTc1MDY4NDQxNn0.PQOFSwMlcWhXqyrHgrDHCAc7gA8DlLocD88LHwtBdIM

### View Purchased Courses
GET http://localhost:3000/purchased-courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5laXRoYWwiLCJpYXQiOjE3NTA0MjA0ODUsImV4cCI6MTc1MDQyNDA4NX0.yiG-NX7MYCRs-NxbBXiqrv-HSsyvb3eccgL-l2eKnMY

### Admin Signup
POST http://localhost:3000/admin/signup
Content-Type: application/json

{
  "username": "admin1",
  "password": "ad1234"
}
###

### Admin Login
POST http://localhost:3000/admin/login
Content-Type: application/json

{
  "username": "admin2",
  "password": "ad1234"
}
###

### new course
POST http://localhost:3000/admin/course
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMiIsImlhdCI6MTc1MDU4OTQxMCwiZXhwIjoxNzUwNTkzMDEwfQ.oUAPgIzklDD6RcPhUZ4EJ81pM7CmVEQ-9oa9TZamDjc
Content-Type: application/json

{
  "title": "Introduction to Node.js"
}
###

###Delete Course (replace courseId and token)
DELETE http://localhost:3000/admin/course/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc1MDQyNDM2NSwiZXhwIjoxNzUwNDI3OTY1fQ.3fhxQvxHwu7DaqdTig-x-ryB5tlXV1DlL1coM0zjDfY 
###

###add content to course (replace courseId and token)
PUT http://localhost:3000/admin/course/1/content
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTc1MDQzMDA0MywiZXhwIjoxNzUwNDMzNjQzfQ.7kT9honja4ADBOOWyUu91_tM6DCwovgjYGH11G6S89A
Content-Type: application/json

{
  "content": "This is a detailed React course for beginners."
}
###

### Get All Courses
GET http://localhost:3000/courses

###

### Purchase Course (replace courseId and token)
POST http://localhost:3000/purchase/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5laXRoYWwiLCJpYXQiOjE3NTA0MjA0ODUsImV4cCI6MTc1MDQyNDA4NX0.yiG-NX7MYCRs-NxbBXiqrv-HSsyvb3eccgL-l2eKnMY
###

### View Purchased Courses
GET http://localhost:3000/purchased-courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5laXRoYWwiLCJpYXQiOjE3NTA0MjA0ODUsImV4cCI6MTc1MDQyNDA4NX0.yiG-NX7MYCRs-NxbBXiqrv-HSsyvb3eccgL-l2eKnMY
